export const SET_LOADING_TYPE = "SET_LOADING_TYPE";
export const SET_REFRESHING_TYPE = "SET_REFRESHING_TYPE";
export const SET_MAIN_NAVIGATOR_TYPE = "SET_NAVIGATOR";
export const SET_FILTER_TYPE = "SET_FILTER_TYPE";
export const SET_PAGE_TYPE = "SET_PAGE_TYPE";
export const SET_PRODUCTS_TYPE = "SET_PRODUCTS_TYPE";
export const SET_PAGE_TITLE_TYPE = "SET_PAGE_TITLE_TYPE";
export const UPDATE_BASKET_TYPE = "UPDATE_BASKET_TYPE";
